# Generated by Django 4.2.7 on 2023-12-21 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='in_watchlist',
            field=models.BooleanField(default=False),
        ),
    ]
